global:
  resolve_timeout: 30s

route:
  receiver: "default"
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10m
  group_by:
    - alertname

inhibit_rules:
  - source_match:
      alertname: HighErrorRate
    target_match:
      alertname: HighWarnRate

receivers:
  - name: "default"
    email_configs:
      - to: "to@example.com"
        from: "from@example.com"
        smarthost: "lab0.sikademo.com:1025"
        require_tls: false
        send_resolved: true
