global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "loki"
    static_configs:
      - targets:
          - "localhost:3100"
  - job_name: "promtail"
    static_configs:
      - targets:
          - "localhost:9080"
